# Generated by Django 3.0.8 on 2021-01-27 19:44

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import randomslugfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=8, max_length=8, unique=True)),
                ('file', models.FileField(upload_to='', verbose_name='Video file')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('recordid', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('response', jsonfield.fields.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='submitted', max_length=10)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motionlab.Video')),
            ],
        ),
    ]
